name: Setup SCCache

on:
  workflow_dispatch:

jobs:
  setup-sccache:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            arch: x86_64
          - os: ubuntu-24.04-arm
            arch: aarch64
          # - os: macos-15-large
          #   arch: x86_64
          # - os: macos-15-xlarge
          #   arch: aarch64
          - os: windows-2025
            arch: x86_64
          - os: windows-11-arm
            arch: aarch64
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install SCCache (Mozilla Action)
        uses: mozilla/sccache-action@v0.0.9
        continue-on-error: true

      - name: Download custom SCCache artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT: a888c16ff2be03c9e7e99f8431186985587cf5b2
          RUN_ID: 18143591494
          SCCACHE_PATH: ${{ env.SCCACHE_PATH }}
        run: |
          echo "Downloading custom SCCache artifact to overwrite the official one..."
          
          ARCH_ID="${{ matrix.arch }}"

          case "${{ runner.os }}" in
            Linux) OS_ID="unknown-linux-musl" ;;
            macOS) OS_ID="apple-darwin" ;;
            Windows) OS_ID="pc-windows-msvc" ;;
          esac

          ARTIFACT_NAME="sccache-$COMMIT-$ARCH_ID-$OS_ID"
          echo "Looking for artifact: $ARTIFACT_NAME"

          ARTIFACT_URL=$(curl -sSL -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/mozilla/sccache/actions/runs/$RUN_ID/artifacts" \
            | jq -r --arg NAME "$ARTIFACT_NAME" '.artifacts[] | select(.name==$NAME) | .archive_download_url')

          if [[ -z "$ARTIFACT_URL" ]]; then
            echo "Artifact not found!"
            exit 1
          fi

          echo "Downloading $ARTIFACT_URL ..."
          curl -L -H "Authorization: Bearer $GITHUB_TOKEN" -o sccache.zip "$ARTIFACT_URL"
          unzip -o sccache.zip -d sccache-bin
        shell: bash

      - name: Install custom SCCache (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          # Fallback caso SCCACHE_PATH não exista
          if [[ -z "$SCCACHE_PATH" ]]; then
            SCCACHE_PATH="$HOME/.local/bin/sccache"
            mkdir -p "$(dirname "$SCCACHE_PATH")"
          fi

          echo "Installing custom SCCache to $SCCACHE_PATH..."

          if [[ ! -f "sccache-bin/sccache" ]]; then
            echo "Error: sccache binary not found in sccache-bin!"
            exit 1
          fi

          rm -f "$SCCACHE_PATH"
          mv sccache-bin/sccache "$SCCACHE_PATH"
          chmod +x "$SCCACHE_PATH"
        shell: bash

      - name: Install custom SCCache (Windows)
        if: runner.os == 'Windows'
        run: |
          # Fallback caso SCCACHE_PATH não exista
          if (-not $env:SCCACHE_PATH) {
            $env:SCCACHE_PATH = "C:\hostedtoolcache\windows\sccache\custom\sccache.exe"
            New-Item -ItemType Directory -Force -Path (Split-Path $env:SCCACHE_PATH)
          }

          Write-Host "Installing custom SCCache to $env:SCCACHE_PATH..."

          if (-not (Test-Path "sccache-bin\sccache.exe")) {
            Write-Error "sccache binary not found in sccache-bin!"
            exit 1
          }

          if (Test-Path $env:SCCACHE_PATH) {
            Write-Host "Removing existing SCCache at $env:SCCACHE_PATH"
            Remove-Item -Force $env:SCCACHE_PATH
          }

          $dest = $env:SCCACHE_PATH -replace '/', '\'
          Move-Item -Force "sccache-bin\sccache.exe" $dest

          Write-Host "SCCache installed at $dest"
        shell: pwsh

      - name: Verify SCCache version
        run: |
          echo "SCCache version:"
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            powershell -Command "& $env:SCCACHE_PATH --version"
          else
            "$SCCACHE_PATH" --version
          fi
        shell: bash
